[versions]
managed-microstream='07.00.00-MS-GA'
reactor-test = '3.4.23'

[libraries]

managed-microstream-storage-embedded-configuration = { module = 'one.microstream:microstream-storage-embedded-configuration', version.ref = 'managed-microstream' }
managed-microstream-cache = { module = 'one.microstream:microstream-cache', version.ref = 'managed-microstream' }
managed-microstream-storage-restservice = { module = 'one.microstream:microstream-storage-restservice', version.ref = 'managed-microstream' }

microstream-rest-gui = { module = 'one.microstream:microstream-storage-restclient-app', version.ref = 'managed-microstream' }
microstream-persistence-binary-jdk8 = { module = 'one.microstream:microstream-persistence-binary-jdk8', version.ref = 'managed-microstream' }

logback-classic = { module = 'ch.qos.logback:logback-classic' }

jupiter-jupiter-params = { module = 'org.junit.jupiter:junit-jupiter-params' }
jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine' }

projectreactor = { module = 'io.projectreactor:reactor-core' }
projectreactor-test = { module = "io.projectreactor:reactor-test", version.ref = 'reactor-test' }
