[versions]
micronaut-docs = "2.0.0"
micronaut = "4.2.0"
groovy = "4.0.14"
kotlin = '1.9.20'
spock = "2.3-groovy-4.0"
testcontainers = "1.19.1"
managed-eclipsestore='1.0.0'

micronaut-aws = "4.1.1"
micronaut-logging = "1.0.0"
micronaut-micrometer = "5.1.2"
micronaut-serde = "2.4.0"
micronaut-sql = "5.2.0"
micronaut-test = "4.0.0"
micronaut-validation = "4.2.0"

[libraries]
micronaut-aws = { module = "io.micronaut.aws:micronaut-aws-bom", version.ref = "micronaut-aws" }
# Required to get dependabot updates for micronaut-core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }

managed-eclipsestore-aws-s3 = { module = 'org.eclipse.store:afs-aws-s3', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-aws-dynamodb = { module = 'org.eclipse.store:afs-aws-dynamodb', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-sql = { module = 'org.eclipse.store:afs-sql', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-storage-embedded-configuration = { module = 'org.eclipse.store:storage-embedded-configuration', version.ref = 'managed-eclipsestore' }
managed-eclipsestore-storage-restservice = { module = 'org.eclipse.store:storage-restservice', version.ref = 'managed-eclipsestore' }

eclipsestore-rest-gui = { module = 'org.eclipse.store:storage-restclient-app', version.ref = 'managed-eclipsestore' }
eclipsestore-persistence-binary-jdk8 = { module = 'org.eclipse.serializer:persistence-binary-jdk8', version.ref = 'managed-eclipsestore' }
eclipsestore-persistence-binary-jdk17 = { module = 'org.eclipse.serializer:persistence-binary-jdk17', version.ref = 'managed-eclipsestore' }

testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
jupiter-jupiter-params = { module = 'org.junit.jupiter:junit-jupiter-params' }
jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api' }
junit-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine' }
kotlin-stdlib = { module = 'org.jetbrains.kotlin:kotlin-stdlib-jdk8', version.ref = 'kotlin' }

awssdk-s3 = { module = 'software.amazon.awssdk:s3' }
awssdk-dynamodb = { module = 'software.amazon.awssdk:dynamodb' }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
